#! /usr/bin/env node

// This is a proxy that runs scripts under ./cmd/{script-name}/index.js
//
// Usage:
//   ./parcel-script clean  

const  { Directories } = require('./platform/directories')
const path = require('node:path')

const scriptPath = path.join(Directories.scripts, process.argv[2], 'index.js')
process.argv[1] = scriptPath
process.argv.splice(2, 1)

require(scriptPath)
